name: Ekonomik Rapor Otomasyonu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Reposuyu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kütüphaneleri yükle
      run: |
        pip install -r requirements.txt

    - name: Raporu oluştur
      run: |
        python Finance.py
