name: Ekonomik Rapor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'  # Her pazar sabahı 09:00 (UTC+3)

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}  # Bu satır çok önemli!

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python Finance.py

