name: Ekonomik Rapor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'  # Her pazar sabahı 09:00 (UTC+3)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Change to project directory
      run: cd $GITHUB_WORKSPACE

    - name: Show current directory
      run: pwd

    - name: List files for debug
      run: ls -la

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Finance.py
      run: python Finance.py
