name: Ekonomik Rapor Otomasyonu

on:
  schedule:
    - cron: '0 6 * * 0'  # Her Pazar 09:00 (Türkiye saatiyle 09:00 = UTC+3 → 06:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gerekli kütüphaneleri yükle
      run: |
        pip install -r requirements.txt

    - name: Python scriptini çalıştır
      run: |
        python Finance.py

